# 连接池 配置
druid:
  url:  jdbc:sqlserver://192.168.3.99:1433;DatabaseName=TopDB
  driver-class-name:  com.microsoft.sqlserver.jdbc.SQLServerDriver
  username:  sa
  password:  top@qadb123
  initial-size:  10
  max-active:  50
  min-idle:  10
  max-wait:  60000
  pool-prepared-statements:  true
  max-pool-prepared-statement-per-connection-size:  20
  validation-query:  SELECT 1
  test-on-borrow:  false
  test-on-return:  false
  test-while-idle:  true
  time-between-eviction-runs-millis:  60000



# dubbo

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 10000
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.cgo.db
  application:
    name: cgo_db
  consumer:
    timeout: 10000
  provider:
    timeout: 10000


# mybatis -- plus  的基本配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/cgo/db/mapper/*Mapper.xml
  type-aliases-package: com.cgo.db.entity








# redis 配置
spring:
  profiles:
    active: config
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 0
    timeout: 3000
    password: 123456

